const PREFIX = `@@invoice`;
const PREFIX_USER = `@@user`;

export const GET_INVOICES = `${PREFIX}/GET_INVOICES`;
export const CREATE_INVOICES = `${PREFIX}/CREATE_INVOICES`;
export const CREATE_INVOICE = `${PREFIX}/CREATE_INVOICE`;
export const CHANGE_INVOICE_MODAL_VISIBILITY = `${PREFIX}/CHANGE_INVOICE_MODAL_VISIBILITY`;
export const LOGOUT = `${PREFIX_USER}/LOGOUT`;
